services:

  postgres:
    image: postgres:16-alpine
    container_name: pdf_chatbot_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: pdf_chatbot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d pdf_chatbot"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: pdf_chatbot_ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
  app:
    build: .
    container_name: pdf_chatbot_app
    restart: unless-stopped
    ports:
      - "8501:8501"
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_started
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: pdf_chatbot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: your_password
      OLLAMA_URL: http://ollama:11434

volumes:
  postgres_data:
  ollama_data: